### ISSUE TITLE
SPM error: NoSources

### ISSUE THREAD

**Issue by damuellen** [kylef/PathKit#11]
I tried to build your Package with the newest version of the Swift Package Manager. I failed with: NoSources(".../Packages/PathKit-0.6.1/Tests/Fixtures").

**Comment by kylef** [comment]
Given the [documentation for SPM](https://github.com/apple/swift-package-manager/blob/87ee762665d64934949603e7ff88309aa49f0e4a/Documentation/SourceLayouts.md#other-rules) says the following:

> - Directories named Tests are ignored
> - Sub directories of a directory named Sources, Source, srcs or src become modules

I'd say this is an SPM bug and not a problem with PathKit.

**Comment by damuellen** [comment]
The newest Version of SPM has support for testing, so the folder isn't ignored. The documentation is out dated.

**Comment by sauliusgrigaitis** [comment]
I've got same issue. Testing feature comes with latest ```DEVELOPMENT-SNAPSHOT-2016-02-25-a``` release, so would be great to get released fix soon.

**Comment by shnhrrsn** [comment]
Running into the same problem with the 2-25 snapshot. Temporary workaround seems to be deleting the Tests directory entirely.

**Comment by kylef** [comment]
Yeah, can't solve this at the moment. There is a bug in the swift package manager's exclude [https://twitter.com/mxcl/status/703073165254070275].

**Comment by kylef** [comment]
I think https://github.com/apple/swift-package-manager/commit/02cf82d947f4d6ff506da61fcbaecc01d06fc4a2 will ultimately solve this problem. Tests shouldn't even be built when using PathKit as a dependency.

**Comment by kylef** [comment]
This can stay open, will need to add the Fixtures directory to excludes once https://github.com/apple/swift-package-manager/pull/152 is merged and released.
