### ISSUE TITLE
Swift Package Manager requires Package.swift

### ISSUE THREAD

**Issue by intere** [kylef/PathKit#17]
Spinning up a new project (using XCode8-Beta4, Apple Swift version 3.0 (swiftlang-800.0.41.2 clang-800.0.36)) requires a non-empty Package.swift file.
```
⇒  swift build
warning: refname '0.6.1' is ambiguous.
warning: refname '0.6.1' is ambiguous.
HEAD is now at 62dca49 Merge pull request #10 from neonichu/linux-support
Resolved version: 0.6.1
Empty manifest file is not supported anymore. Use `swift package init` to autogenerate.
error: The package at `/Users/internicolae/Code/personal/From JSON/Packages/PathKit.git' has no Package.swift for the specific version: 0.6.1
```

**Comment by huawei-brice** [comment]
The master branch has a Package.swift now, but we need a version tag to use it.

**Comment by kylef** [comment]
Support for Swift 3 has been added in [PathKit 0.7.0](https://github.com/kylef/PathKit/releases/tag/0.7.0).
