### ISSUE TITLE
Support for Carthage dropped?

### ISSUE THREAD

**Issue by njdehoog** [kylef/PathKit#20]
Has support for Carthage been dropped? I'm trying to build PathKit 0.7.0 using Carthage but no schemes are built. I checked the repo and I see that the .xcworkspace and .xcodeproj directories have gone. Would it be possible to bring these back? Carthage needs a scheme to be able to build the framework.

**Comment by JamieWhite** [comment]
I'd love to know why this was too. I've got a fork with a hacked together `xcodeproj`. I'm wondering if there is any appetite from @kylef for me to tidy that up and PR it.

**Comment by dostrander** [comment]
Any word on this?

**Comment by kylef** [comment]
> Has support for Carthage been dropped?

Carthage was never actually supported, it may have worked, but it wasn't supported.

> I checked the repo and I see that the .xcworkspace and .xcodeproj directories have gone.

You can use the following to create an Xcode project if you want to integrate with Xcode:

```shell
$ swift package generate-xcodeproj
```

**Comment by JamieWhite** [comment]
Any reason for not wanting to support Carthage?

**Comment by kylef** [comment]
It's not that I don't want to support it. Carthage has a large barrier because it requires library authors to use a specific IDE (Xcode) and enforces opinions on the library and how it would be integrated.

**Comment by kylef** [comment]
You can follow the instructions at https://fuller.li/posts/using-swift-package-manager-with-carthage/ to integrate PathKit with Carthage.
