### ISSUE TITLE
Going from absolute path to relative?

### ISSUE THREAD

**Issue by eonist** [kylef/PathKit#34]
Is it possible to go from absolute path to relative?

Thanks ✌️

**Comment by kylef** [comment]
I don't think there is anything to do this at the moment. If you're interested in contributing that feature I'd certainly welcome it.

**Comment by eonist** [comment]
Sure I can PR. I found a way. This is from my own code lib: 

```swift
/**
     * from user agnostic to absolute URL
     */
    var tildePath:String {return NSString(string: self).expandingTildeInPath}/*Convenince*/
    /**
     * Makes file paths user agnostic (~ instad of hardcoded user)
     * NOTE: from absolute to "relative" URL
     * EXAMPLE: "Users/John/Desktop".tildify//Output:~/Desktop
     */
    var tildify:String {return NSString(string:self).abbreviatingWithTildeInPath}/*Convenince*/
    

```

**Comment by kylef** [comment]
"tildify" is already supported, it's called [`abbreviate`](https://github.com/kylef/PathKit/blob/f3e8fa6/Sources/PathKit.swift#L155). I think that is something different than making a path relative. The relative would be relative to the current working directory whereas abbreviate is just abbreviating a path replacing a users home directory.

**Comment by eonist** [comment]
You mean like resolving ../../ etc or? what would absolute to relative look like for you?

**Comment by neoneye** [comment]
I have made separate repo, [SwiftyRelativePath](https://github.com/neoneye/SwiftyRelativePath), for just this purpose.

```
let url0 = URL(fileURLWithPath: "/computer/qubit/17")
let url1 = URL(fileURLWithPath: "/computer/lab")
url0.relativePath(from: url1) // -> "../qubit/17"
```
