### ISSUE TITLE
New Tag for SPM 4.0

### ISSUE THREAD

**Issue by PoissonBallon** [kylef/PathKit#40]
Hi,

Can we have a new tag for target SPM 4.0 and Spectre 0.8.0 ?
https://github.com/kylef/PathKit/pull/39#issuecomment-337740842

**Comment by yonaskolb** [comment]
Yes please! This would resolve the conflict in versions with Commander, Spectre and Pathkit

**Comment by daveanderson** [comment]
I need this as well. Thank you!

**Comment by yonaskolb** [comment]
@kylef bump

**Comment by kylef** [comment]
Made 0.9.0 https://github.com/kylef/PathKit/commit/404d60fd725d1ba7dbf55cb95a3046285a066169

**Comment by yonaskolb** [comment]
Thank you Kyle! Merry Christmas! 🎄😀
