### ISSUE TITLE
PathKit build fails through Carthage

### ISSUE THREAD

**Issue by Danappelxx** [kylef/PathKit#5]
Example:

```bash
$ cat Cartfile
github "kylef/PathKit"
$ carthage bootstrap
*** No Cartfile.resolved found, updating dependencies
*** Fetching PathKit
*** Checking out PathKit at "0.5.0"
*** xcodebuild output can be found in /var/folders/76/q9xfxg_s187bkp6gyxqqxw8r0000gn/T/carthage-xcodebuild.f9pQMQ.log
*** Building scheme "PathKit" in PathKit.xcworkspace
``` 

So carthage builds PathKit, which is great. However, the framework can't be used for whatever reason.

```bash
$ cat main.swift
import PathKit
print(Path.current)
$ ls Carthage/Build/Mac
PathKit.framework
$ swiftc main.swift -F Carthage/Build/Mac/
$ ./main
dyld: Library not loaded: @rpath/PathKit.framework/Versions/A/PathKit
  Referenced from: /Users/dan/Desktop/test/./main
  Reason: image not found
[1]    45284 trace trap  ./main
```

It works perfectly fine with other frameworks, for example Commander.

Thoughts?

**Comment by kylef** [comment]
Does `PathKit.framework` get built into `Carthage/Build/Mac/`?

**Comment by Danappelxx** [comment]
Yup - it's in the second code block (I edited my post right after I pressed submit).

**Comment by kylef** [comment]
Just curious, can you try the following before running `./main`:

```shell
$ install_name_tool -add_rpath "@executable_path/Carthage/Build/Mac/"  "main"
```

**Comment by Danappelxx** [comment]
Huh... that worked. I've never heard of that command before. What does it do?

Output:
```bash
$ ./main
/Users/dan/Desktop/test
```

**Comment by kylef** [comment]
I've written about it at https://github.com/kylef/Commander#installation

When you said it works perfectly for other frameworks, we're you doing this the exact same way? With `swiftc`?

**Comment by Danappelxx** [comment]
Yup - take a look at the build script for [MastCLI](https://github.com/danappelxx/mastcli) if you need an example.

**Comment by kylef** [comment]
@Danappelxx I think MastCLI is only working because you haven't used any APIs from Commander only imported it.

Once you try using Commander, without the Commander framework available in the rpath it will not run too.

**Comment by Danappelxx** [comment]
Src/main.swift uses Commander.

**Comment by kylef** [comment]
Ah missed that file, was looking in `src/Command.swift`.

**Comment by Danappelxx** [comment]
Hm... adding `install_name_tool -add_rpath "@executable_path/Carthage/Build/Mac/"  "bin/mast"` to my setup script in MastCLI doesn't fix the PathKit issue I'm having. Would you happen to know why?

**Comment by kylef** [comment]
@Danappelxx The rpath you've shown is relative to executable path, and `Carthage` isn't inside the `bin` directory.

Should become:

```shell
$ install_name_tool -add_rpath "@executable_path/../Carthage/Build/Mac/" "bin/mast"
```

**Comment by Danappelxx** [comment]
Man, you really know your stuff - thanks!

**Comment by kylef** [comment]
Going to close this since it looks like we've resolved the problem.
