### ISSUE TITLE
Foundation Dependency & Linux support

### ISSUE THREAD

**Issue by cezheng** [kylef/PathKit#8]
I noticed that the README of Conche says 

```
The purpose of Conche is that it is a build system separate from Xcode which can work on various platforms such as Linux.
```

Yet as one of Conche's dependencies, PathKit currently relies on NSFileManager, so reimplementing those methods that uses Foundation classes will be necessary once Swift is on Linux.

**Comment by kylef** [comment]
Yes, this is already in progress and tracked inside #4.
