### ISSUE TITLE
Xcode 13 compiler error

### ISSUE THREAD

**Issue by chilimovpasha** [kylef/PathKit#82]
Hello  everyone 👋
Seems like not all errors have been fixed. Could you please help?)))

![Screenshot 2021-09-23 at 17 44 53](https://user-images.githubusercontent.com/9354461/134529565-a7a89fd7-4072-4b25-a36e-b0a9cb95deac.png)

**Comment by chilimovpasha** [comment]
Sorry, my bad. remove extra dependency. I don't know why it's happen but now it works.

**Comment by kylef** [comment]
The screenshot is not PathKit source and is a file from a different dependency you are using -> https://github.com/tuist/XcodeProj/blob/main/Sources/XcodeProj/Extensions/Path%2BExtras.swift .

**Comment by chilimovpasha** [comment]
Omg, double my bad ) sorry for interrupt

**Comment by kylef** [comment]
It looks like there's a patch released a few hours ago in https://github.com/tuist/XcodeProj/releases/tag/8.3.1
